default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: postgresql

test:
  <<: *default
  database: postgresql

production:
  <<: *default
  database: postgresql
