default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: bus-system

test:
  <<: *default
  database: bus-system

production:
  <<: *default
  database: bus-system
